using System.Text.Json.Serialization;
using RevenueCat.NET.Models.Common;
using RevenueCat.NET.Models.Enums;
using RevenueCat.NET.Models.Entitlements;

namespace RevenueCat.NET.Models.Subscriptions;

/// <summary>
/// Represents a subscription in RevenueCat.
/// </summary>
public class Subscription : BaseModel
{
    /// <summary>
    /// The customer ID who owns this subscription.
    /// </summary>
    [JsonPropertyName("customer_id")]
    public string CustomerId { get; set; } = string.Empty;

    /// <summary>
    /// The original customer ID who first purchased this subscription.
    /// </summary>
    [JsonPropertyName("original_customer_id")]
    public string OriginalCustomerId { get; set; } = string.Empty;

    /// <summary>
    /// The product ID associated with this subscription.
    /// </summary>
    [JsonPropertyName("product_id")]
    public string? ProductId { get; set; }

    /// <summary>
    /// The date when the subscription started in milliseconds since epoch.
    /// </summary>
    [JsonPropertyName("starts_at")]
    public long StartsAt { get; set; }

    /// <summary>
    /// The date when the current period started in milliseconds since epoch.
    /// </summary>
    [JsonPropertyName("current_period_starts_at")]
    public long CurrentPeriodStartsAt { get; set; }

    /// <summary>
    /// The date when the current period ends in milliseconds since epoch.
    /// </summary>
    [JsonPropertyName("current_period_ends_at")]
    public long? CurrentPeriodEndsAt { get; set; }

    /// <summary>
    /// The date when the subscription ends/ended in milliseconds since epoch.
    /// </summary>
    [JsonPropertyName("ends_at")]
    public long? EndsAt { get; set; }

    /// <summary>
    /// Whether this subscription currently gives access to content.
    /// </summary>
    [JsonPropertyName("gives_access")]
    public bool GivesAccess { get; set; }

    /// <summary>
    /// Whether there is a pending payment for this subscription.
    /// </summary>
    [JsonPropertyName("pending_payment")]
    public bool PendingPayment { get; set; }

    /// <summary>
    /// The auto-renewal status of the subscription.
    /// </summary>
    [JsonPropertyName("auto_renewal_status")]
    public AutoRenewalStatus AutoRenewalStatus { get; set; }

    /// <summary>
    /// The current status of the subscription.
    /// </summary>
    [JsonPropertyName("status")]
    public SubscriptionStatus Status { get; set; }

    /// <summary>
    /// Total revenue generated by this subscription in USD.
    /// </summary>
    [JsonPropertyName("total_revenue_in_usd")]
    public MonetaryAmount TotalRevenueInUsd { get; set; } = new();

    /// <summary>
    /// The offering ID that was presented when this subscription was purchased.
    /// </summary>
    [JsonPropertyName("presented_offering_id")]
    public string? PresentedOfferingId { get; set; }

    /// <summary>
    /// The entitlements granted by this subscription.
    /// </summary>
    [JsonPropertyName("entitlements")]
    public ListResponse<Entitlement> Entitlements { get; set; } = new();

    /// <summary>
    /// The environment where this subscription was purchased.
    /// </summary>
    [JsonPropertyName("environment")]
    public Enums.Environment Environment { get; set; }

    /// <summary>
    /// The store where this subscription was purchased.
    /// </summary>
    [JsonPropertyName("store")]
    public Store Store { get; set; }

    /// <summary>
    /// The store-specific subscription identifier.
    /// </summary>
    [JsonPropertyName("store_subscription_identifier")]
    public string StoreSubscriptionIdentifier { get; set; } = string.Empty;

    /// <summary>
    /// The ownership type of this subscription.
    /// </summary>
    [JsonPropertyName("ownership")]
    public Ownership Ownership { get; set; }

    /// <summary>
    /// Pending changes to this subscription, if any.
    /// </summary>
    [JsonPropertyName("pending_changes")]
    public PendingChanges? PendingChanges { get; set; }

    /// <summary>
    /// The country code (ISO alpha-2) where the subscription was purchased.
    /// </summary>
    [JsonPropertyName("country")]
    public string? Country { get; set; }

    /// <summary>
    /// URL to manage this subscription.
    /// </summary>
    [JsonPropertyName("management_url")]
    public string? ManagementUrl { get; set; }
}
