using System.Text.Json.Serialization;

namespace RevenueCat.NET.Models.Subscriptions;

/// <summary>
/// Represents a transaction associated with a subscription.
/// </summary>
public class SubscriptionTransaction : BaseModel
{
    /// <summary>
    /// The subscription ID this transaction belongs to.
    /// </summary>
    [JsonPropertyName("subscription_id")]
    public string SubscriptionId { get; set; } = string.Empty;
    
    /// <summary>
    /// The store-specific transaction identifier.
    /// </summary>
    [JsonPropertyName("store_transaction_identifier")]
    public string StoreTransactionIdentifier { get; set; } = string.Empty;
    
    /// <summary>
    /// The date when the transaction occurred in milliseconds since epoch.
    /// </summary>
    [JsonPropertyName("purchased_at")]
    public long PurchasedAt { get; set; }
    
    /// <summary>
    /// Revenue generated by this transaction in USD.
    /// </summary>
    [JsonPropertyName("revenue_in_usd")]
    public MonetaryAmount RevenueInUsd { get; set; } = new();
}
