using System.Text.Json.Serialization;
using RevenueCat.NET.Models.Common;
using RevenueCat.NET.Models.Enums;
using RevenueCat.NET.Models.Entitlements;

namespace RevenueCat.NET.Models.Purchases;

/// <summary>
/// Represents a one-time purchase in RevenueCat.
/// </summary>
public class Purchase : BaseModel
{
    /// <summary>
    /// The customer ID who made this purchase.
    /// </summary>
    [JsonPropertyName("customer_id")]
    public string CustomerId { get; set; } = string.Empty;

    /// <summary>
    /// The original customer ID who first made this purchase.
    /// </summary>
    [JsonPropertyName("original_customer_id")]
    public string OriginalCustomerId { get; set; } = string.Empty;

    /// <summary>
    /// The product ID that was purchased.
    /// </summary>
    [JsonPropertyName("product_id")]
    public string ProductId { get; set; } = string.Empty;

    /// <summary>
    /// The date when the purchase was made in milliseconds since epoch.
    /// </summary>
    [JsonPropertyName("purchased_at")]
    public long PurchasedAt { get; set; }

    /// <summary>
    /// Revenue generated by this purchase in USD.
    /// </summary>
    [JsonPropertyName("revenue_in_usd")]
    public MonetaryAmount RevenueInUsd { get; set; } = new();

    /// <summary>
    /// The quantity purchased.
    /// </summary>
    [JsonPropertyName("quantity")]
    public int Quantity { get; set; }

    /// <summary>
    /// The status of the purchase.
    /// </summary>
    [JsonPropertyName("status")]
    public PurchaseStatus Status { get; set; }

    /// <summary>
    /// The offering ID that was presented when this purchase was made.
    /// </summary>
    [JsonPropertyName("presented_offering_id")]
    public string? PresentedOfferingId { get; set; }

    /// <summary>
    /// The entitlements granted by this purchase.
    /// </summary>
    [JsonPropertyName("entitlements")]
    public ListResponse<Entitlement> Entitlements { get; set; } = new();

    /// <summary>
    /// The environment where this purchase was made.
    /// </summary>
    [JsonPropertyName("environment")]
    public Enums.Environment Environment { get; set; }

    /// <summary>
    /// The store where this purchase was made.
    /// </summary>
    [JsonPropertyName("store")]
    public Store Store { get; set; }

    /// <summary>
    /// The store-specific purchase identifier.
    /// </summary>
    [JsonPropertyName("store_purchase_identifier")]
    public string StorePurchaseIdentifier { get; set; } = string.Empty;

    /// <summary>
    /// The ownership type of this purchase.
    /// </summary>
    [JsonPropertyName("ownership")]
    public Ownership Ownership { get; set; }

    /// <summary>
    /// The country code (ISO alpha-2) where the purchase was made.
    /// </summary>
    [JsonPropertyName("country")]
    public string? Country { get; set; }
}
